### ISSUE TITLE
Rarity

### ISSUE THREAD

**Issue by ImaEternal** [galperins4/NFT_Generator#5]
.

**Comment by galperins4** [comment]
hi! Can you provide a little more details and an example of how it might work. It's possible, but I'd need a little more information on your suggestion

**Comment by ImaEternal** [comment]
.

**Comment by icar112** [comment]
Hello sir, thank you for the beautiful script. It really helped me to complete the work. I only have a question, how can I update the metadata hash after uploading the images, because according to what I understood, after the task of creating the images is finished, I upload it to a pinata, and then I take the hash and put it in a file nft dot py and restart the file again, but how can I update the jason files without reproducing the images again, because in this case I used 1500px X 1500px images, and it produced about 10,000 and took me about two days of work.. I mean, it needs the same period Just for the sake of updating the jason files, the question is how can I update the jason files without reproducing the images. Thank you, sorry for the length.
